name: Actions Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  actions-check:
    runs-on: ubuntu-latest

    steps:
      - name: Dummy check
        run: echo "actions-check passed"